version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./front:/usr/share/nginx/html
    ports:
      - "8001:80"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    ports:
      - "8000:8000"
    working_dir: /usr/src/app
    command: npm start
    environment:
      - NODE_ENV=development
