version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./front:/usr/share/nginx/html
    ports:
      - "8002:80"
    depends_on:
      - frontend

  frontend:
    build: ./front
    ports:
      - "8080:8080"
    volumes:
      - ./front:/usr/src/app
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
