version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=adminn  # Change this username
      - DJANGO_SUPERUSER_EMAIL=newadmin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpassword

  frontend:
    build: ./front
    ports:
      - "8080:8080"
    volumes:
      - ./front:/usr/src/app
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./front:/usr/share/nginx/html
    ports:
      - "8005:80"
    depends_on:
      - frontend

volumes:
  postgres_data:
