# Generated by Django 4.2.14 on 2024-09-19 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='account_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
