# Generated by Django 4.2.14 on 2024-09-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
