# Generated by Django 4.2.14 on 2024-09-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_is_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
    ]
