# Generated by Django 5.1.2 on 2024-10-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_is_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
