# Generated by Django 5.1.2 on 2024-10-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_account_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
