# Generated by Django 5.1.2 on 2024-10-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_online_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='online_status',
        ),
    ]
